# Use same base image
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app + tests
COPY . .

# Ensure Python can import app.py
ENV PYTHONPATH=/app

# Run tests
CMD ["pytest", "-v"]
